[versions]
komponenter = "2.0.172"
behandlingsflyt = "0.0.667"
tilgang = "1.0.242"

[libraries]
# AAP Kelvin
httpklient = { module = "no.nav.aap.kelvin:httpklient", version.ref = "komponenter" }
dbconnect = { module = "no.nav.aap.kelvin:dbconnect", version.ref = "komponenter" }
dbmigrering = { module = "no.nav.aap.kelvin:dbmigrering", version.ref = "komponenter" }
dbtest = { module = "no.nav.aap.kelvin:dbtest", version.ref = "komponenter" }
infrastructure = { module = "no.nav.aap.kelvin:infrastructure", version.ref = "komponenter" }
server = { module = "no.nav.aap.kelvin:server", version.ref = "komponenter" }
motor = { module = "no.nav.aap.kelvin:motor", version.ref = "komponenter" }
motorApi = { module = "no.nav.aap.kelvin:motor-api", version.ref = "komponenter" }
verdityper = { module = "no.nav.aap.kelvin:verdityper", version.ref = "komponenter" }
tidslinje = { module = "no.nav.aap.kelvin:tidslinje", version.ref = "komponenter" }
ktorOpenapiGenerator = { module = "no.nav.aap.kelvin:ktor-openapi-generator", version.ref = "komponenter" }
motorTestUtils = { module = "no.nav.aap.kelvin:motor-test-utils", version.ref = "komponenter" }
tilgangPlugin = { module = "no.nav.aap.tilgang:plugin", version.ref = "tilgang" }
behandlingsflytKontrakt = { module = "no.nav.aap.behandlingsflyt:kontrakt", version.ref = "behandlingsflyt" }