CREATE TABLE TILKJENT_YTELSE_TREKK
(
    ID                      BIGSERIAL       NOT NULL PRIMARY KEY,
    TILKJENT_YTELSE_ID      BIGINT          NOT NULL REFERENCES TILKJENT_YTELSE(ID),
    DATO                    DATE            NOT NULL,
    BELOP                   INT             NOT NULL
);

CREATE INDEX IDX_TILKJENT_YTELSE_ID ON TILKJENT_YTELSE_TREKK (TILKJENT_YTELSE_ID);
CREATE UNIQUE INDEX UIDX_TILKJENT_YTELSE_ID_DATO ON TILKJENT_YTELSE_TREKK (TILKJENT_YTELSE_ID, DATO);

ALTER TABLE TILKJENT_YTELSE ADD COLUMN NY_MELDEPERIODE DATERANGE DEFAULT NULL;

CREATE TABLE TREKK
(
    ID                      BIGSERIAL       NOT NULL PRIMARY KEY,
    SAKSNUMMER              VARCHAR(20)     NOT NULL,
    BEHANDLINGSREFERANSE    UUID            NOT NULL,
    DATO                    DATE            NOT NULL,
    BELOP                   INT             NOT NULL,
    OPPRETTET_TIDSPUNKT     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    AKTIV                   BOOLEAN         NOT NULL DEFAULT TRUE,
    OPPDATERT_TIDSPUNKT     TIMESTAMP
);

CREATE INDEX IDX_SAKSNUMMER ON TREKK (SAKSNUMMER);
CREATE UNIQUE INDEX UIDX_SAKSNUMMER_DATO ON TREKK (SAKSNUMMER, DATO) WHERE AKTIV = TRUE;


CREATE TABLE TREKK_POSTERING
(
    ID                      BIGSERIAL       NOT NULL PRIMARY KEY,
    TREKK_ID                BIGINT          NOT NULL REFERENCES TREKK(ID),
    DATO                    DATE            NOT NULL,
    BELOP                   INT             NOT NULL,
    OPPRETTET_TIDSPUNKT     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_TREKK_ID ON TREKK_POSTERING (TREKK_ID);
CREATE UNIQUE INDEX UIDX_DATO_SLETTET ON TREKK_POSTERING (TREKK_ID, DATO);
