CREATE TABLE TILKJENT_YTELSE
(
    ID                      BIGSERIAL       NOT NULL PRIMARY KEY,
    SAKSNUMMER              VARCHAR(10)     NOT NULL,
    BEHANDLING_REF          UUID            NOT NULL,
    FORRIGE_BEHANDLING_REF  UUID,
    PERSON_IDENT            VARCHAR(11)     NOT NULL,
    VEDTAKSTIDSPUNKT        TIMESTAMP       NOT NULL,
    BESLUTTER_ID            VARCHAR(20)     NOT NULL,
    SAKSBEHANDLER_ID        VARCHAR(20)     NOT NULL
);


CREATE TABLE TILKJENT_PERIODE
(
    ID                 BIGSERIAL       NOT NULL PRIMARY KEY,
    PERIODE            DATERANGE       NOT NULL,
    VENTEDAGER_SAMORDNING BOOLEAN      NOT NULL,
    DAGSATS            NUMERIC(21, 0)  NOT NULL,
    GRUNNLAG           NUMERIC(21, 0)  NOT NULL,
    GRADERING          SMALLINT        NOT NULL,
    GRUNNBELOP         NUMERIC(21)     NOT NULL,
    ANTALL_BARN        SMALLINT        NOT NULL,
    BARNETILLEGG       NUMERIC(21)     NOT NULL,
    GRUNNLAGSFAKTOR    NUMERIC(21, 10) NOT NULL,
    BARNETILLEGGSATS   NUMERIC         NOT NULL,
    REDUSERT_DAGSATS   NUMERIC(21, 0)  NOT NULL,
    TILKJENT_YTELSE_ID BIGINT          NOT NULL REFERENCES TILKJENT_YTELSE (ID)
);