CREATE TABLE MELDEPERIODE_UTBETALING_MAPPING (
    ID BIGSERIAL NOT NULL,
    SAK_UTBETALING_ID BIGINT NOT NULL,
    MELDEPERIODE DATERANGE NOT NULL,
    UTBETALING_ID UUID NOT NULL,
    PRIMARY KEY (ID)
);

