ALTER TABLE UTBETALING_STATUS_LINJE ADD COLUMN PERIODE DATERANGE;

UPDATE UTBETALING_STATUS_LINJE
SET PERIODE = DATERANGE(FOM, TOM, '[]');

ALTER TABLE UTBETALING_STATUS_LINJE DROP COLUMN FOM;
ALTER TABLE UTBETALING_STATUS_LINJE DROP COLUMN TOM;

ALTER TABLE UTBETALING_STATUS_LINJE ALTER COLUMN PERIODE SET NOT NULL;