-- Legger til manglende indekser for å støtte spørringer i repositoriene.
-- Hovedsakelig FK-felt og WHERE-/JOIN-kolonner som mangler indeks i dag.

-- TILKJENT_YTELSE: SAKSNUMMER brukes i join fra TILKJENT_YTELSE_AVVENT
CREATE INDEX IDX_TILKJENT_YTELSE_SAKSNUMMER ON TILKJENT_YTELSE (SAKSNUMMER);

-- TILKJENT_PERIODE: FK uten indeks, brukes i WHERE TILKJENT_YTELSE_ID = ?
CREATE INDEX IDX_TILKJENT_PERIODE_TILKJENT_YTELSE_ID ON TILKJENT_PERIODE (TILKJENT_YTELSE_ID);

-- TILKJENT_YTELSE_AVVENT: FK uten indeks, brukes i WHERE TILKJENT_YTELSE_ID = ?
CREATE INDEX IDX_TILKJENT_YTELSE_AVVENT_TY_ID ON TILKJENT_YTELSE_AVVENT (TILKJENT_YTELSE_ID);

-- UTBETALING: oppslag på saksnummer for aktive (ikke slettede) utbetalinger
CREATE INDEX IDX_UTBETALING_SAKSNUMMER ON UTBETALING (SAKSNUMMER) WHERE SLETTET = FALSE;

-- UTBETALING: oppslag på UTBETALING_REF (UNIQUE-constraint ble droppet i V1.8)
CREATE INDEX IDX_UTBETALING_UTBETALING_REF ON UTBETALING (UTBETALING_REF);

-- UTBETALING: hentUtbetalingerSomManglerKvittering filtrerer på status og slettet=false
CREATE INDEX IDX_UTBETALING_STATUS_AKTIV ON UTBETALING (UTBETALING_STATUS) WHERE SLETTET = FALSE;

-- UTBETALING: FK uten indeks
CREATE INDEX IDX_UTBETALING_TILKJENT_YTELSE_ID ON UTBETALING (TILKJENT_YTELSE_ID);
CREATE INDEX IDX_UTBETALING_SAK_UTBETALING_ID ON UTBETALING (SAK_UTBETALING_ID);

-- UTBETALINGSPERIODE: FK uten indeks, brukes i WHERE UTBETALING_ID = ?
CREATE INDEX IDX_UTBETALINGSPERIODE_UTBETALING_ID ON UTBETALINGSPERIODE (UTBETALING_ID);

-- UTBETALING_AVVENT: brukes i WHERE UTBETALING_ID = ?
CREATE INDEX IDX_UTBETALING_AVVENT_UTBETALING_ID ON UTBETALING_AVVENT (UTBETALING_ID);

-- MELDEPERIODE_UTBETALING_MAPPING: brukes i WHERE SAK_UTBETALING_ID = ?
CREATE INDEX IDX_MELDEPERIODE_MAPPING_SAK_UTBETALING_ID ON MELDEPERIODE_UTBETALING_MAPPING (SAK_UTBETALING_ID);
