
-- Knytter utbetalinger til et saksnummer
CREATE TABLE SAK_UTBETALING
(
    ID                      BIGSERIAL       NOT NULL PRIMARY KEY,
    SAKNUMMER               VARCHAR(10)     NOT NULL UNIQUE,
    OPPRETTET_TIDSPUNKT     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FORSTE_UTBETALINGSDATO  NUMERIC(2)      NOT NULL,
    ANDRE_UTBETALINGSDATO   NUMERIC(2)      NOT NULL
);

-- Tilstander for en utbetalingsforespørsel
CREATE TYPE UTBETALING_STATUS AS ENUM ('NY', 'SENDT', 'BEKREFTET');

-- Deltajer for en utbetaling
CREATE TABLE UTBETALING_DETALJER
(
    ID                 BIGSERIAL       NOT NULL PRIMARY KEY,
    PERIODE            DATERANGE       NOT NULL,
    DAGSATS            NUMERIC(21)     NOT NULL,
    GRUNNLAG           NUMERIC(21)     NOT NULL,
    GRADERING          SMALLINT        NOT NULL,
    GRUNNBELOP         NUMERIC(21)     NOT NULL,
    ANTALL_BARN        SMALLINT        NOT NULL,
    BARNETILLEGG       NUMERIC(21)     NOT NULL,
    GRUNNLAGSFAKTOR    NUMERIC(21, 10) NOT NULL,
    BARNETILLEGGSATS   NUMERIC         NOT NULL,
    REDUSERT_DAGSATS   NUMERIC(21)     NOT NULL

);

-- Forespørsel om å gjøre en utbetaling
CREATE TABLE UTBETALING_REQUEST
(
    ID                      BIGSERIAL           NOT NULL PRIMARY KEY,
    SAK_UTBETALING_ID       BIGINT              NOT NULL REFERENCES SAK_UTBETALING (ID),
    UTBETALING_DETALJER     BIGINT              NOT NULL REFERENCES UTBETALING_DETALJER (ID),
    UTBETALING_STATUS       UTBETALING_STATUS   NOT NULL
);

-- Ferdigstilt utbetaling
CREATE TABLE UTBETALING
(
    ID                      BIGSERIAL           NOT NULL PRIMARY KEY,
    SAK_UTBETALING_ID       BIGINT              NOT NULL REFERENCES SAK_UTBETALING (ID),
    UTBETALING_DETALJER     BIGINT              NOT NULL REFERENCES UTBETALING_DETALJER (ID)
);
