
-- Knytter utbetalinger til et saksnummer
CREATE TABLE SAK_UTBETALING
(
    ID                      BIGSERIAL       NOT NULL PRIMARY KEY,
    SAKSNUMMER              VARCHAR(10)     NOT NULL UNIQUE,
    OPPRETTET_TIDSPUNKT     TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    AKTIV                   BOOLEAN         NOT NULL DEFAULT TRUE
);


-- Plan for utbetaling
CREATE TABLE UTBETALING
(
    ID                      BIGSERIAL           NOT NULL PRIMARY KEY,
    SAK_UTBETALING_ID       BIGINT              NOT NULL REFERENCES SAK_UTBETALING (ID),
    TILKJENT_YTELSE_ID      BIGINT              NOT NULL REFERENCES TILKJENT_YTELSE (ID),
    UTBETALING_OVERSENDT    TIMESTAMP           NOT NULL,
    UTBETALING_BEKREFTET    TIMESTAMP,
    UTBETALING_STATUS       VARCHAR(20)         NOT NULL
);

-- Periode for en utbetaling
CREATE TABLE UTBETALINGSPERIODE
(
    ID                      BIGSERIAL       NOT NULL PRIMARY KEY,
    UTBETALING_ID           BIGINT          NOT NULL REFERENCES UTBETALING (ID),
    UTBETALINGSPERIODE_TYPE VARCHAR(20) NOT NULL,
    PERIODE                 DATERANGE       NOT NULL,
    VENTEDAGER_SAMORDNING   BOOLEAN         NOT NULL,
    DAGSATS                 NUMERIC(21)     NOT NULL,
    GRUNNLAG                NUMERIC(21)     NOT NULL,
    GRADERING               SMALLINT        NOT NULL,
    GRUNNBELOP              NUMERIC(21)     NOT NULL,
    ANTALL_BARN             SMALLINT        NOT NULL,
    BARNETILLEGG            NUMERIC(21)     NOT NULL,
    GRUNNLAGSFAKTOR         NUMERIC(21, 10) NOT NULL,
    BARNETILLEGGSATS        NUMERIC         NOT NULL,
    REDUSERT_DAGSATS        NUMERIC(21)     NOT NULL
);
