CREATE TABLE JOBB_KOMMENTAR
(
    ID            BIGSERIAL    NOT NULL PRIMARY KEY,
    JOBB_ID       BIGINT       NOT NULL REFERENCES JOBB (ID),
    SKREVET_AV    TEXT         NOT NULL,
    TEKST         TEXT         NOT NULL,
    OPPRETTET_TID TIMESTAMP(3) NOT NULL
);

CREATE INDEX IDX_JOBB_KOMMENTAR_JOBB_ID ON JOBB_KOMMENTAR (JOBB_ID);
