CREATE TABLE UTBETALINGSMELDING (
    ID                  BIGSERIAL       NOT NULL PRIMARY KEY,
    SAK_UTBETALING_ID   BIGINT          NOT NULL,
    TILKJENT_YTELSE_ID  BIGINT          NOT NULL,
    MELDING             JSONB           NOT NULL,
    OPPRETTET_TID       TIMESTAMP(3)    NOT NULL
);

CREATE UNIQUE INDEX UIDX_UTBETALINGSMELDING_TILKJENT ON UTBETALINGSMELDING (TILKJENT_YTELSE_ID);