ALTER TABLE UTBETALINGSMELDING ADD COLUMN REFERANSE UUID;
ALTER TABLE UTBETALINGSMELDING ADD COLUMN MELDINGSTYPE VARCHAR(30);

UPDATE UTBETALINGSMELDING UM
    SET REFERANSE = TY.BEHANDLING_REF
    FROM TILKJENT_YTELSE TY
    WHERE TY.ID = UM.TILKJENT_YTELSE_ID AND REFERANSE IS NULL;

UPDATE UTBETALINGSMELDING UM
    SET MELDINGSTYPE = 'UTBETALING'
    WHERE MELDINGSTYPE IS NULL;

ALTER TABLE UTBETALINGSMELDING
    ALTER COLUMN REFERANSE SET NOT NULL;

ALTER TABLE UTBETALINGSMELDING
    ALTER COLUMN MELDINGSTYPE SET NOT NULL;


DROP INDEX UIDX_UTBETALINGSMELDING_TILKJENT;
CREATE UNIQUE INDEX UIDX_UTBETALINGSMELDING_REFERANSE ON UTBETALINGSMELDING (REFERANSE);
