CREATE TABLE GJELDENDE_AVVENT_PERIODE (
    ID                  BIGSERIAL    NOT NULL PRIMARY KEY,
    SAK_UTBETALING_ID   BIGINT       NOT NULL REFERENCES SAK_UTBETALING (ID),
    PERIODE             DATERANGE    NOT NULL,
    AKTIV               BOOLEAN      NOT NULL,
    OPPRETTET_TID       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE INDEX IDX_GJELDENEDE_AVVENT_PERIODE_SAK_UTBETALING_ID ON GJELDENDE_AVVENT_PERIODE (SAK_UTBETALING_ID);
