ALTER TABLE UTBETALING_STATUS
    ADD COLUMN UTBETALINGSMELDING_ID BIGINT REFERENCES UTBETALINGSMELDING(ID);

UPDATE UTBETALING_STATUS US
    SET UTBETALINGSMELDING_ID = UM.ID
    FROM UTBETALINGSMELDING UM
    WHERE UM.TILKJENT_YTELSE_ID = US.TILKJENT_YTELSE_ID AND UTBETALINGSMELDING_ID IS NULL;

