DELETE FROM UTBETALING_AVVENT;
DELETE FROM UTBETALINGSPERIODE;
DELETE FROM UTBETALING;

ALTER TABLE UTBETALINGSPERIODE ADD COLUMN UTBETALINGSDATO DATE NOT NULL;

DELETE FROM TILKJENT_PERIODE;
DELETE FROM TILKJENT_YTELSE;

ALTER TABLE TILKJENT_PERIODE ADD COLUMN UTBETALINGSDATO DATE NOT NULL;
