name: release

on:
    workflow_dispatch:
        inputs:
            cluster:
                description: Cluster
                required: true
                default: dev-gcp
                type: choice
                options:
                    - dev-gcp
    push:
        branches: [ main ]
        paths-ignore:
            - '.github/**'

jobs:
    gradle:
        ## push til main eller etter branch (e.g. dependabot) er merget
        if: github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        permissions:
            contents: write
            actions: read
            checks: write
            id-token: write
        uses: navikt/aap-workflows/.github/workflows/gradle-build.yml@main
        secrets: inherit
        with:
            publish-typescript: false
    publish-kontrakt:
        needs: gradle
        permissions:
            contents: write
            packages: write
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: 'temurin'
            - uses: gradle/actions/setup-gradle@v4
            - uses: paulhatch/semantic-version@v5.4.0
              id: tag
              with:
                  change_path: "api-kontrakt/"
                  bump_each_commit: true
                  tag_prefix: ""
                  bump_each_commit_patch_pattern: ''
                  major_pattern: "(MAJOR)" # If major bump, include this in commit message
            - id: notes
              if: ${{ steps.tag.outputs.changed == 'true' }}
              run: |
                randomDelimiter=${RANDOM}
                text=$(git --no-pager log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h %s" | sed ':a;N;$!ba;s/\n/\n\n/g')
                echo 'CHANGELOG<<$randomDelimiter' >> $GITHUB_OUTPUT
                echo -e "$text" >> $GITHUB_OUTPUT
                echo '$randomDelimiter' >> $GITHUB_OUTPUT
            - if: ${{ steps.tag.outputs.changed == 'true' }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  ./gradlew -Pversion=${{ steps.tag.outputs.version }} publish
            - uses:  softprops/action-gh-release@v2
              if: ${{ steps.tag.outputs.changed == 'true' }}
              id: create_release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.tag.outputs.version }}
                  name: ${{ steps.tag.outputs.version }}
                  body: |
                      Endringer siden sist:
                      ${{ steps.notes.outputs.CHANGELOG }}

    dev:
        ## push til main eller etter branch (e.g. dependabot) er merget
        if: github.event.pull_request.merged || github.event_name == 'push' || github.event.inputs.cluster == 'dev-gcp'
        permissions:
            contents: read
            id-token: write
        needs: gradle
        uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
        secrets: inherit
        with:
            cluster: dev-gcp
            manifest: .nais/app-dev.yaml

    prod:
        ## push til main eller etter branch (e.g. dependabot) er merget
        if: github.event.pull_request.merged || github.event_name == 'push' || github.event.inputs.cluster == 'prod-gcp'
        permissions:
            contents: read
            id-token: write
        needs: gradle
        uses: navikt/aap-workflows/.github/workflows/deploy.yml@main
        secrets: inherit
        with:
            cluster: prod-gcp
            manifest: .nais/app-prod.yaml